terraform_backend_defaults:
  type: gcs
  configuration:
    bucket: yashroff-terraform-state
vars:
  # [RECOMMENDED] Enable Slurm Native Authentication. MUNGE is deprecating and scheduled for complete removal on July 31, 2026.
  # For upgrade instructions, see docs/slurm-native-auth-migration-guide.md.
  enable_slurm_auth: true
  deployment_name: yashroff-g4-flex
  project_id: northam-ce-mlai-tpu
  region: us-central1
  zone: us-central1-b

  # G4 Slurm Configuration
  slurm_cluster_name: yashroff-flex-g4
  g4_static_cluster_size: 2
  machine_type: g4-standard-24
  
  # G4 Networking
  network_name_system: default
  subnetwork_name_system: default

  # Enable DWS Flex-start
  g4_dws_flex_enabled: true

